version: '3'

services:
  graphite:
    build: ./graphite
    ports:
      - "80:80"
    volumes:
      - /opt/graphite/storage:/opt/graphite/storage
      - /opt/graphite/conf:/opt/graphite/conf
    networks:
      - stats
  statsd:
    build: ./statsd
    volumes:
      - /opt/statsd:/opt/statsd
    networks:
      - stats
  statoshi:
    build: ./statoshi
    ports:
      - 8333:8333
    volumes:
      - ~/.bitcoin:/root/.bitcoin
    networks:
      - stats

networks:
  stats:
    driver: bridge
