version: '3'

services:
  statsd-graphite:
    image: bitcoin-stats_statsd-graphite
    ports:
      - "80:80"
      - "8128:8125"
    network_mode: 'host'
    # volumes:
    #   - /opt/graphite/storage:/opt/graphite/storage
    #   - /opt/graphite/conf:/opt/graphite/conf
    # networks:
    #   - hostn
  statoshi:
    image: bitcoin-stats_statoshi
    ports:
      - "8333:8333"
    expose:
      - "8125"
    network_mode: 'host'
    # volumes:
    #   - ~/.bitcoin:/root/.bitcoin
    # networks:
    #   - stats

# networks:
#   stats:
#     driver: bridge
